[package]
name = "dbfs2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rvfs = {git = "https://github.com/Godones/rvfs.git"}
jammdb = {git = "https://github.com/Godones/jammdb.git"}
spin = "0.9.2"
log = "0.4.14"