[package]
name = "dbfs2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rvfs = {path = "../rvfs"}
jammdb = {git = "https://github.com/Godones/jammdb.git"}
spin = "0.9.2"



[dev-dependencies]
env_logger = "0.9.0"