[package]
name = "dbfs2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jammdb = {path = "../jammdb"}
rvfs = {path = "../rvfs"}
spin = "0.9.2"